apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Pod
metadata:
  name: tester
  namespace: test
spec:
  containers:
  - name: tester
    image: alpine
    command: ["sleep"]
    args: ["38640"]
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: tester
spec:
  containers:
  - name: tester
    image: alpine
    command: ["sleep"]
    args: ["38640"]
  restartPolicy: Never

